### ISSUE TITLE
Pose optimization error for Mixamo dataset

### ISSUE THREAD

**Issue by cshen11** [LemonATsu/A-NeRF#20]
Hi, thanks for the great work. I was training A-NeRF on the pre-processed Mixamo dataset and encountered an **RuntimeError: CUDA error: device-side assert triggered**. Can you please see how to fix it?

I followed the instruction and used the given mixamo.txt. Nothing changed in the code. More detailed error info is: 
> ../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

[Above assertion printed multiple times with thread being [18,0,0] to [44,0,0]]

> Traceback (most recent call last):
  File "XYZ/A-NeRF/run_nerf.py", line 625, in <module>
    train()
  File "XYZ/A-NeRF/run_nerf.py", line 559, in train
    kp_val, bone_val, skt_val, _, _ = popt_layer(render_data["kp_idxs"])
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "XYZ/A-NeRF/core/pose_opt.py", line 313, in forward
    return self.calculate_kinematic(idxs, rest_pose_idxs)
  File "XYZ/A-NeRF/core/pose_opt.py", line 387, in calculate_kinematic
    pelvis, bone = self.idx_to_params(unique_idxs)
  File "XYZ/A-NeRF/core/pose_opt.py", line 326, in idx_to_params
    return pelvis, bones[idx]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**This error can be eliminated if opt_pose is set False or pose_opt setting (below) is removed in mixamo.txt:**

> opt_rot6d = True
> opt_pose_tol = 0.01
> opt_pose_type = BE
> opt_pose = True
> opt_pose_step = 20
> opt_pose_lrate = 0.0005
> opt_pose_decay_rate = 1.
> opt_pose_lrate_decay = 2
> opt_pose_decay_unit = 1000
> opt_pose_joint = True
> opt_pose_coef = 2.0
> opt_framecode = True

**Comment by cshen11** [comment]
Looks like a similar problem in #9

**Comment by LemonATsu** [comment]
Hi, I have pushed a fix for this issue, it should resolve the problem.

**Comment by cshen11** [comment]
Yes, it resolved this problem. Thank you very much!
